project:
  type: website

website:
  title: "Yunzhi Chen's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022/blog-yche0537
format:
  html:
    theme: Morph
    css: styles.css



